## holds all inputs and validations that are accessed in the add person and home windows

# demographics
RACES = ["", "White", "Black", "Asian", "Hispanic", "Other"]
HAIR_COLORS = ["", "Black", "Brown", "Blonde", "Red", "Gray", "White", "Other"]
EYE_COLORS = ["", "Blue", "Brown", "Green", "Grey", "Hazel", "Other"]
SEXES = ["", "Male", "Female"]
STATE_CODES = [
    "",
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
]
